/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora.atividade;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Thiago54053176
 */
public class CalculadoraTela extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraTela
     */
    public CalculadoraTela() {
        initComponents();
    }

    public JButton getBtn_division() {
        return btn_division;
    }

    public JLabel getResultado() {
        return resultado;
    }

    public void setResultado(JLabel resultado) {
        this.resultado = resultado;
    }

    public JTextField getValor1() {
        return valor1;
    }

    public void setValor1(JTextField valor1) {
        this.valor1 = valor1;
    }

    public JTextField getValor2() {
        return valor2;
    }

    public void setValor2(JTextField valor2) {
        this.valor2 = valor2;
    }

    public void setBtn_division(JButton btn_division) {
        this.btn_division = btn_division;
    }

    public JButton getBtn_multiplicacao() {
        return btn_multiplicacao;
    }

    public void setBtn_multiplicacao(JButton btn_multiplicacao) {
        this.btn_multiplicacao = btn_multiplicacao;
    }

    public JButton getBtn_soma() {
        return btn_soma;
    }

    public void setBtn_soma(JButton btn_soma) {
        this.btn_soma = btn_soma;
    }

    public JButton getBtn_sub() {
        return btn_sub;
    }

    public void setBtn_sub(JButton btn_sub) {
        this.btn_sub = btn_sub;
    }

    public JTextField getjTextField1() {
        return valor2;
    }

    public void setjTextField1(JTextField jTextField1) {
        this.valor2 = jTextField1;
    }

    public JTextField getjTextField2() {
        return valor1;
    }

    public void setjTextField2(JTextField jTextField2) {
        this.valor1 = jTextField2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_soma = new javax.swing.JButton();
        btn_sub = new javax.swing.JButton();
        btn_division = new javax.swing.JButton();
        btn_multiplicacao = new javax.swing.JButton();
        valor2 = new javax.swing.JTextField();
        valor1 = new javax.swing.JTextField();
        resultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_soma.setText("Soma");
        btn_soma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_somaMouseClicked(evt);
            }
        });

        btn_sub.setText("Subtração");
        btn_sub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_subMouseClicked(evt);
            }
        });

        btn_division.setText("Divisão");
        btn_division.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_divisionMouseClicked(evt);
            }
        });

        btn_multiplicacao.setText("Multiplicação");
        btn_multiplicacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_multiplicacaoMouseClicked(evt);
            }
        });

        valor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor2ActionPerformed(evt);
            }
        });

        valor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor1ActionPerformed(evt);
            }
        });

        resultado.setText("Resultado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_soma)
                    .addComponent(btn_division))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_multiplicacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_sub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(valor1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(valor2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(resultado)
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultado))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_soma)
                    .addComponent(btn_sub))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_division)
                    .addComponent(btn_multiplicacao))
                .addContainerGap(322, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valor2ActionPerformed

    private void valor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valor1ActionPerformed

    private void btn_somaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_somaMouseClicked
    
            double v1 = Double.parseDouble(valor1.getText());
            double v2 = Double.parseDouble(valor2.getText());
            double result = v1 + v2;
            resultado.setText(String.valueOf(result));
            
            valor1.setText("");
            valor2.setText("");
            
    }//GEN-LAST:event_btn_somaMouseClicked

    private void btn_subMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_subMouseClicked
            
           double v1 = Double.parseDouble(valor1.getText());
            double v2 = Double.parseDouble(valor2.getText());
            double result = v1 - v2;
            resultado.setText(String.valueOf(result));
            
            valor1.setText("");
            valor2.setText("");

    }//GEN-LAST:event_btn_subMouseClicked

    private void btn_divisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_divisionMouseClicked
    
           double v1 = Double.parseDouble(valor1.getText());
            double v2 = Double.parseDouble(valor2.getText());
            double result = v1 / v2;
            resultado.setText(String.valueOf(result));
            
            valor1.setText("");
            valor2.setText("");
        
    }//GEN-LAST:event_btn_divisionMouseClicked

    private void btn_multiplicacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_multiplicacaoMouseClicked
        
           double v1 = Double.parseDouble(valor1.getText());
            double v2 = Double.parseDouble(valor2.getText());
            double result = v1 * v2;
            resultado.setText(String.valueOf(result));
            
            valor1.setText("");
            valor2.setText("");

    }//GEN-LAST:event_btn_multiplicacaoMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_division;
    private javax.swing.JButton btn_multiplicacao;
    private javax.swing.JButton btn_soma;
    private javax.swing.JButton btn_sub;
    private javax.swing.JLabel resultado;
    private javax.swing.JTextField valor1;
    private javax.swing.JTextField valor2;
    // End of variables declaration//GEN-END:variables
}
