/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package imcpessoa;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Thiago54053176
 */
public class IMCatividadeDESCRICAO extends javax.swing.JFrame {

    /**
     * Creates new form IMCatividadeDESCRICAO
     */
    public IMCatividadeDESCRICAO() {
        initComponents();
    }

    public JTextField getAltura_pessoa() {
        return altura_pessoa;
    }

    public void setAltura_pessoa(JTextField altura_pessoa) {
        this.altura_pessoa = altura_pessoa;
    }

    public JButton getCalcular() {
        return calcular;
    }

    public void setCalcular(JButton calcular) {
        this.calcular = calcular;
    }

    public JTextField getIdade_pessoa() {
        return idade_pessoa;
    }

    public void setIdade_pessoa(JTextField idade_pessoa) {
        this.idade_pessoa = idade_pessoa;
    }

    public JTextField getNome_pessoa() {
        return nome_pessoa;
    }

    public void setNome_pessoa(JTextField nome_pessoa) {
        this.nome_pessoa = nome_pessoa;
    }

    public JTextField getPeso_pessoa() {
        return peso_pessoa;
    }

    public void setPeso_pessoa(JTextField peso_pessoa) {
        this.peso_pessoa = peso_pessoa;
    }

    public JTextField getResultado() {
        return resultado;
    }

    public void setResultado(JTextField resultado) {
        this.resultado = resultado;
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nome_pessoa = new javax.swing.JTextField();
        idade_pessoa = new javax.swing.JTextField();
        altura_pessoa = new javax.swing.JTextField();
        peso_pessoa = new javax.swing.JTextField();
        resultado = new javax.swing.JTextField();
        calcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("NOME");

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("IDADE");

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("RESULTADO");

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("PESO");

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setText("ALTURA");

        nome_pessoa.setBackground(new java.awt.Color(255, 255, 255));
        nome_pessoa.setForeground(new java.awt.Color(0, 0, 0));
        nome_pessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_pessoaActionPerformed(evt);
            }
        });

        idade_pessoa.setBackground(new java.awt.Color(255, 255, 255));
        idade_pessoa.setForeground(new java.awt.Color(0, 0, 0));
        idade_pessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idade_pessoaActionPerformed(evt);
            }
        });

        altura_pessoa.setBackground(new java.awt.Color(255, 255, 255));
        altura_pessoa.setForeground(new java.awt.Color(0, 0, 0));
        altura_pessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altura_pessoaActionPerformed(evt);
            }
        });

        peso_pessoa.setBackground(new java.awt.Color(255, 255, 255));
        peso_pessoa.setForeground(new java.awt.Color(0, 0, 0));
        peso_pessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peso_pessoaActionPerformed(evt);
            }
        });

        resultado.setBackground(new java.awt.Color(255, 255, 255));
        resultado.setForeground(new java.awt.Color(0, 0, 0));
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });

        calcular.setBackground(new java.awt.Color(255, 51, 51));
        calcular.setForeground(new java.awt.Color(255, 255, 255));
        calcular.setText("CALCULAR");
        calcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcularMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idade_pessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nome_pessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2))
                    .addComponent(calcular)
                    .addComponent(peso_pessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(altura_pessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nome_pessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idade_pessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultado)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(altura_pessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(peso_pessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(calcular)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nome_pessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_pessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_pessoaActionPerformed

    private void idade_pessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idade_pessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idade_pessoaActionPerformed

    private void altura_pessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altura_pessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_altura_pessoaActionPerformed

    private void peso_pessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peso_pessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peso_pessoaActionPerformed

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoActionPerformed

    private void calcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcularMouseClicked
       
         double p1 = Double.parseDouble(peso_pessoa.getText());
         double a1 = Double.parseDouble(altura_pessoa.getText());
         
         
        double result = p1 / (a1 * a1);
        
        String classificacao = null;
        
        if(result < 18.5) {
              classificacao = "Abaixo do peso, tome cuidado...";
        } 
       else if (result >= 18.5 && result < 24.9){
                classificacao = "peso normal, parabéns...";
         }
         
       else if (result >= 25 && result < 29.9){
                classificacao = "sobrepeso, dá para reagir";
         }
         
            
       else if (result >= 30 && result < 34.9){
                classificacao = "Obesidade grau I, sua saúde está ruim..";
         }
         
         
       else if (result >= 35 && result < 39.9){
                classificacao = "Obesidade grau II, emergência, muude seus hábitos...";
         }
         
         
       else if (result > 40.0){
                classificacao = "Obesidade grau III, sua saúde está em perigo.";
         }
         
  resultado.setText(nome_pessoa.getText() + ", você tem " + idade_pessoa.getText() + " anos, " + "seu IMC é: " + String.format("%.2f", result) + ", e a sua classificação é: " + classificacao);
                       
        
          
       
    }//GEN-LAST:event_calcularMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IMCatividadeDESCRICAO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IMCatividadeDESCRICAO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IMCatividadeDESCRICAO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IMCatividadeDESCRICAO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IMCatividadeDESCRICAO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField altura_pessoa;
    private javax.swing.JButton calcular;
    private javax.swing.JTextField idade_pessoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nome_pessoa;
    private javax.swing.JTextField peso_pessoa;
    private javax.swing.JTextField resultado;
    // End of variables declaration//GEN-END:variables
}
